// <auto-generated />
using System;
using ElectroformLite.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectroformLite.API.Migrations
{
    [DbContext(typeof(ElectroformDbContext))]
    partial class ElectroformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ElectroformLite.Domain.Models.Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DataGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DataTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataGroupId");

                    b.HasIndex("DataTemplateId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DataGroupTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DataGroupTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("DataGroups");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroupTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DataGroupTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataGroupTypeId");

                    b.ToTable("DataGroupTemplates");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroupType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DataGroupTypes");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DataTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeId");

                    b.ToTable("DataTemplates");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DataTypes");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.Data", b =>
                {
                    b.HasOne("ElectroformLite.Domain.Models.DataGroup", null)
                        .WithMany("UserData")
                        .HasForeignKey("DataGroupId");

                    b.HasOne("ElectroformLite.Domain.Models.DataTemplate", null)
                        .WithMany("UserData")
                        .HasForeignKey("DataTemplateId");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroup", b =>
                {
                    b.HasOne("ElectroformLite.Domain.Models.DataGroupTemplate", null)
                        .WithMany("DataGroups")
                        .HasForeignKey("DataGroupTemplateId");

                    b.HasOne("ElectroformLite.Domain.Models.User", null)
                        .WithMany("DataGroups")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroupTemplate", b =>
                {
                    b.HasOne("ElectroformLite.Domain.Models.DataGroupType", null)
                        .WithMany("DataGroupTemplates")
                        .HasForeignKey("DataGroupTypeId");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataTemplate", b =>
                {
                    b.HasOne("ElectroformLite.Domain.Models.DataType", null)
                        .WithMany("DataTemplates")
                        .HasForeignKey("DataTypeId");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.Document", b =>
                {
                    b.HasOne("ElectroformLite.Domain.Models.Template", null)
                        .WithMany("Documents")
                        .HasForeignKey("TemplateId");

                    b.HasOne("ElectroformLite.Domain.Models.User", null)
                        .WithMany("Documents")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroup", b =>
                {
                    b.Navigation("UserData");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroupTemplate", b =>
                {
                    b.Navigation("DataGroups");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataGroupType", b =>
                {
                    b.Navigation("DataGroupTemplates");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataTemplate", b =>
                {
                    b.Navigation("UserData");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.DataType", b =>
                {
                    b.Navigation("DataTemplates");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.Template", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ElectroformLite.Domain.Models.User", b =>
                {
                    b.Navigation("DataGroups");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
